{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./cmp.nix
    ./conform.nix
    ./gitsigns.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./neo-tree.nix
    ./nvim-autopairs.nix
    ./nvim-web-devicons.nix
    ./telescope.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./undotree.nix
  ];
}
